seed: 123456

n_sim: 10

branch_length: 0.1

start: 1

end: 251

replicate_n: 10

dir:
  /scratch/saracv/CFTP_testConvergence

methSite_genomicDist: 
  spatial_str.RData

prior_distributions:
  # Gamma distribution
  alpha_pI:
    shape: 3
    scale: 0.0333333333  # 1/30 as a decimal value
  # Gamma distribution
  beta_pI:
    shape: 3
    scale: 0.3333333333  # 1/3 as a decimal value
  # Gamma distribution
  alpha_pNI:
    shape: 3
    scale: 0.0333333333  # 1/30 as a decimal value
  # Gamma distribution
  beta_pNI:
    shape: 3
    scale: 0.3333333333  # 1/3 as a decimal value
  # Gamma distribution
  alpha_mI:
    shape: 3
    scale: 0.0333333333  # 1/30 as a decimal value
  # Gamma distribution
  beta_mI:
    shape: 3
    scale: 0.1666666667  # 1/6 as a decimal value
  # Gamma distribution
  alpha_mNI:
    shape: 3
    scale: 0.1666666667  # 1/6 as a decimal value
  # Gamma distribution
  beta_mNI:
    shape: 3
    scale: 0.0333333333  # 1/30 as a decimal value
  # Exponential distribution
  alpha_Ri:
    rate: 0.5  # 1/2 as a decimal value
  # Exponential distribution
  mu:
    rate: 50
  # Uniform distribution
  iota:
    min: 0
    max: 1
  # Uniform distribution
  tree_scale:
    min: 0.1
    max: 20

# Number of CpGs per structure
CpG_n: 100

# Number of structures of each type
Str_n: 20




  



