# Import os for path manipulations
import os

# Set the configfile directive
configfile: "config.yaml"

# Rule to get the spatial_str.RData file for the genomic region to simulate
rule get_spatial_str:
    output:
        spatial_str = os.path.join(config["dir"], config["methSite_genomicDist"])
    params:
    	out_dir = config["dir"],
    	out_name = config["methSite_genomicDist"],
    	n_CpG = config["CpG_n"],
    	n_str = config["Str_n"]
    shell:
        """
        Rscript scripts/get_spatial_str.R --dir {params.out_dir} --file-name {params.out_name} --CpG-n {params.n_CpG} --str-n {params.n_str}
        """

# Rule to generate design files
rule set_design:
    input:
        spatial_str = os.path.join(config["dir"], config["methSite_genomicDist"])
    output:
        design_file= config["dir"] + "/design.RData"  # Path for the design file
    params:
        sim_number = config["n_sim"],
        seed=config["seed"],
        alpha_pI_shape=config["prior_distributions"]["alpha_pI"]["shape"],
        alpha_pI_scale=config["prior_distributions"]["alpha_pI"]["scale"],
        beta_pI_shape=config["prior_distributions"]["beta_pI"]["shape"],
        beta_pI_scale=config["prior_distributions"]["beta_pI"]["scale"],
        alpha_pNI_shape=config["prior_distributions"]["alpha_pNI"]["shape"],
        alpha_pNI_scale=config["prior_distributions"]["alpha_pNI"]["scale"],
        beta_pNI_shape=config["prior_distributions"]["beta_pNI"]["shape"],
        beta_pNI_scale=config["prior_distributions"]["beta_pNI"]["scale"],
        alpha_mI_shape=config["prior_distributions"]["alpha_mI"]["shape"],
        alpha_mI_scale=config["prior_distributions"]["alpha_mI"]["scale"],
        beta_mI_shape=config["prior_distributions"]["beta_mI"]["shape"],
        beta_mI_scale=config["prior_distributions"]["beta_mI"]["scale"],
        alpha_mNI_shape=config["prior_distributions"]["alpha_mNI"]["shape"],
        alpha_mNI_scale=config["prior_distributions"]["alpha_mNI"]["scale"],
        beta_mNI_shape=config["prior_distributions"]["beta_mNI"]["shape"],
        beta_mNI_scale=config["prior_distributions"]["beta_mNI"]["scale"],
        alpha_Ri_rate=config["prior_distributions"]["alpha_Ri"]["rate"],
        mu_rate=config["prior_distributions"]["mu"]["rate"],
        iota_min=config["prior_distributions"]["iota"]["min"],
        iota_max=config["prior_distributions"]["iota"]["max"]
        
    shell:
        """
        Rscript scripts/set_sim_design.R \
            --n-sim {params.sim_number} \
            --output {output.design_file} \
            --genome-dist {input.spatial_str} \
            --seed {params.seed} \
            --alpha_pI_shape {params.alpha_pI_shape} \
            --alpha_pI_scale {params.alpha_pI_scale} \
            --beta_pI_shape {params.beta_pI_shape} \
            --beta_pI_scale {params.beta_pI_scale} \
            --alpha_pNI_shape {params.alpha_pNI_shape} \
            --alpha_pNI_scale {params.alpha_pNI_scale} \
            --beta_pNI_shape {params.beta_pNI_shape} \
            --beta_pNI_scale {params.beta_pNI_scale} \
            --alpha_mI_shape {params.alpha_mI_shape} \
            --alpha_mI_scale {params.alpha_mI_scale} \
            --beta_mI_shape {params.beta_mI_shape} \
            --beta_mI_scale {params.beta_mI_scale} \
            --alpha_mNI_shape {params.alpha_mNI_shape} \
            --alpha_mNI_scale {params.alpha_mNI_scale} \
            --beta_mNI_shape {params.beta_mNI_shape} \
            --beta_mNI_scale {params.beta_mNI_scale} \
            --alpha_Ri_rate {params.alpha_Ri_rate} \
            --mu_rate {params.mu_rate} \
            --iota_min {params.iota_min} \
            --iota_max {params.iota_max} \
        """

# Rule to run the simulations
rule run_sim:
    input:
        design_file=config["dir"] + "/design.RData"  # Path for the design file
    params:
        out_dir = config["dir"],
        branch_length = config["branch_length"],
        start = config["start"],
        end = config["end"],
        rep_n = config["replicate_n"]
    output:
        expand(
            config["dir"] + "/CFTP_testConvergence_paramsID_{n}_rep_{r}_{s}.RData",
            n=[str(i).zfill(len(str(config["n_sim"]))) for i in range(1, config["n_sim"] + 1)],
            r=[str(i).zfill(len(str(config["replicate_n"]))) for i in range(1, config["replicate_n"] + 1)],
            s=[str(i).zfill(len(str(config["end"])) + 1) for i in range(config["start"] - 1, config["end"] + 1)]
        ),
        expand(
            config["dir"] + "/CFTP_testConvergence_paramsID_{n}_rep_{r}_cftp.RData",
            n=[str(i).zfill(len(str(config["n_sim"]))) for i in range(1, config["n_sim"] + 1)],
            r=[str(i).zfill(len(str(config["replicate_n"]))) for i in range(1, config["replicate_n"] + 1)]
        )

    shell:
        """	
        Rscript scripts/run_sim.R --design-file {input.design_file} --dir {params.out_dir} --branch-length {params.branch_length} --start {params.start} --end {params.end} --replicate-n {params.rep_n} 
        """


# Rule to compute the mean Correlation
rule compute_meanCor:
    input:
        expand(
            config["dir"] + "/CFTP_testConvergence_paramsID_{n}_rep_{r}_{s}.RData",
            n=[str(i).zfill(len(str(config["n_sim"]))) for i in range(1, config["n_sim"] + 1)],
            r=[str(i).zfill(len(str(config["replicate_n"]))) for i in range(1, config["replicate_n"] + 1)],
            s=[str(i).zfill(len(str(config["end"])) + 1) for i in range(config["start"] - 1, config["end"] + 1)]
        ),
        expand(
            config["dir"] + "/CFTP_testConvergence_paramsID_{n}_rep_{r}_cftp.RData",
            n=[str(i).zfill(len(str(config["n_sim"]))) for i in range(1, config["n_sim"] + 1)],
            r=[str(i).zfill(len(str(config["replicate_n"]))) for i in range(1, config["replicate_n"] + 1)]
        )

    output:
        expand(
            config["dir"] + "/summaryStats_CFTP_testConvergence_paramsID_{n}_rep_{r}.RData",
            n=[str(i).zfill(len(str(config["n_sim"]))) for i in range(1, config["n_sim"] + 1)],
            r=[str(i).zfill(len(str(config["replicate_n"]))) for i in range(1, config["replicate_n"] + 1)]
        ),
        expand(
            config["dir"] + "/summaryStats_CFTP_testConvergence_paramsID_{n}_cftp.RData",
            n=[str(i).zfill(len(str(config["n_sim"]))) for i in range(1, config["n_sim"] + 1)]
        )
    params:
        dir = config["dir"],
        design_file = config["dir"] + "/design.RData",
        n_sim = config["n_sim"],
        start = config["start"],
        end = config["end"],
        rep_n = config["replicate_n"]

    shell:
        """	
        Rscript scripts/compute_meanCor.R --design-file {params.design_file} --dir {params.dir} --n-sim {params.n_sim} --start {params.start} --end {params.end} --replicate-n {params.rep_n} 
        """


